### PR TITLE
[Done] Merge branch 'homebrew/master' into 'davidchall/master'

### PR DESCRIPTION
**Pull request by maelvls**
I had to re-open a new PR because PR #3 was using 'master' (I should have thought about creating a dedicated branch 🙄).

Summary of previous PR:

@davidchall commented:

> I think we should keep `GIT_AUTHOR_NAME` separate from `#{tap.user}` to retain the functionality used by BrewTestBot etc. For our case, these two variables will just be set equal.

I answered:

> Any idea on the `GIT_AUTHOR_NAME` vs. `HOMEBREW_GIT_NAME`? As I understand it, `HOMEBREW_GIT_NAME` is used for selecting to which Github repo the push will happen on. It can be set using `--git-name`. What do you think about changing `GIT_AUTHOR_NAME ` to `HOMEBREW_GIT_NAME`?

So I replaced `GIT_AUTHOR_NAME` by `HOMEBREW_GIT_NAME`. What should we do now?

### CODE REVIEW

**Comment by maelvls** [comment]
Oh, I think I had a wrong mental model of the Homebrew/homebrew-core bottling process. As I understand it now, I think this line:

https://github.com/davidchall/homebrew-test-bot/blob/ec3b498a9d65790e8613448e121f61b3e4fbb4ff/cmd/brew-test-bot.rb#L1318

introduced in commit https://github.com/davidchall/homebrew-test-bot/commit/ec3b498a9d65790e8613448e121f61b3e4fbb4ff will break the Homebrew/homebrew-core's Jenkins. When a PR is opened and the formula needs a bottle, Jenkins will build the bottle and

1. upload the bottle as "unpublished".
2. commit and push the DSL to BrewTestBot/Homebrew-core with the `pr-1234` tag.

Then a Homebrew maintainer will `brew pull --bottle 1234` which will do two things:

1. switch the bottle in bintray from "unpublished" to "published"
2. fetch the `pr-1234` tag, rebase it on top of `Homebrew/homebrew-core` and push it there


I made a small drawing that helps me remembering how the whole process works; @MikeMcQuaid, did I draw the workflow correctly?

homebrew_homebrew-core workflow - transparent png

I guess we could create a flag that will force the publishing to be immediate, like `--bintray-immediate-publish` or smth like this

**Comment by MikeMcQuaid** [comment]
> When a PR is opened and the formula needs a bottle, Jenkins will build the bottle and
> 
> upload the bottle as "unpublished".
> commit and push the DSL to BrewTestBot/Homebrew-core with the pr-1234 tag.
> Then a Homebrew maintainer will brew pull --bottle 1234 which will do two things:
> 
> switch the bottle in bintray from "unpublished" to "published"
> fetch the pr-1234 tag, rebase it on top of Homebrew/homebrew-core and push it there

This is all correct 👍 

> A Homebrew user notices the change and opens a pull request

Some upstreams do this as part of their release process. Additionally some maintainers (mostly `@ilovezfs`) use https://github.com/homebrew/homebrew-livecheck to check these somewhat automatically.

> brew pull rebases and pushes

This is done by the maintainer and not automatically by `brew pull`.

---

Otherwise: yes, this is all correct! Well done. If you have this in some sort of editable format we might add it to our docs?

**Comment by maelvls** [comment]
Thanks for the precisions on the `brew pull` details!

[Here is an archive](https://github.com/davidchall/homebrew-test-bot/files/1826438/Homebrew_homebrew-core_workflow.zip) with a PNG (with transparency), opaque PNG, transparent SVG, opaque SVG and PDF. Also the source is [here](https://www.lucidchart.com/documents/view/d6a4384f-2faf-4fef-b9c2-ceb1dd417037/0) (lucidchart). You can use this drawing how ever you like!

**Update:** now that I think of it, I should probably have used a free software with a free format... sorry for that 😞
**Update2:** I updated the PNG, PDF & SVG ([version2_png_pdf_svg.zip](https://github.com/davidchall/homebrew-test-bot/files/1828514/png_pdf_svg.zip)). You can edit it in Visio also: [Homebrew_homebrew-core workflow.vdx.zip](https://github.com/davidchall/homebrew-test-bot/files/1828516/Homebrew_homebrew-core.workflow.vdx.zip)

**Comment by maelvls** [comment]
Hi!

I merged the new stuff from homebrew-core.

I noticed that @sjackman added on March 31st the `--root-url` argument that does exactly the same as @davidchall's TAP_BOTTLE_DOMAIN (i.e., change the `root_url` value of the
formula which is, in our case, the bintray URL).

In order to keep things tidy, I propose to only keep `--root-url=`. But it is going to break me and david's travis builds.

**Comment by MikeMcQuaid** [comment]
I'd like to suggest in the interests of everyone's sanity that you try to submit some of these changes to Homebrew/homebrew-test-bot before we diverge much further. I'm going to unsubscribe from this thread after this point; please don't CC me, thanks!

**Comment by maelvls** [comment]
Very sorry for the noise, I didn't think about the mental burden CCing would mean. I'll publish this PR to the homebrew-core asap.

**Comment by davidchall** [comment]
Hey @maelvalais - I'm afraid I'm not going to be able to review this, and I've got completely out of step with Homebrew anyhow. I recommend that you open the PR to `homebrew-core` directly from your own fork. Looking forward to seeing it merged, and reading up on how to get this working for my own tap.

One question: is AWS the only place to store the intermediate bottle DSL before pushing to the tap repo? Although this is free for the first year, I think you have to pay beyond that.

**Comment by maelvls** [comment]
Hi! No problem, I understand. I'll open a PR to homebrew-core asap.

About AWS S3, you are totally right: after 12 months, it costs! Right now, it costs me about 0.05€/month (travis-ci with a daily cron so many S3 pushes/fetches). I personally don't really mind, but if someone comes up with a better solution I would be very happy to try it out and switch to it!

**Pull request closed without merging**
